name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd sec.club
    - name: npm install, test, build
      run: |
        npm ci
        npm test
        npm run build
      env:
        CI: true
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.1.0
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}